# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HomeKitProjectIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HomeKitProjectIOS

end

target 'HomeKitProjectIOS WatchKit App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HomeKitProjectIOS WatchKit App

end

target 'HomeKitProjectIOS WatchKit Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HomeKitProjectIOS WatchKit Extension

end
